### ISSUE TITLE
memory error when using theory 400

### ISSUE THREAD

**Issue by tgiani** [NNPDF/nnpdf#1642] opened 2022-12-02 09:50 UTC
I m trying to run a fit using theory 400, and all my jobs are failing with an error like 
```
[INFO]: Generating layers for experiment ATLAS
[CRITICAL]: Bug in n3fit ocurred. Please report it.
Traceback (most recent call last):
  File "/data/theorie/tgiani/nnpdfgit/nnpdf/n3fit/src/n3fit/scripts/n3fit_exec.py", line 264, in run
    super().run()
  File "/data/theorie/tgiani/nnpdfgit/nnpdf/validphys2/src/validphys/app.py", line 159, in run
    super().run()
  File "/data/theorie/tgiani/miniconda3/envs/nnpdf-dev/lib/python3.8/site-packages/reportengine/app.py", line 374, in run
    rb.execute_sequential()
  File "/data/theorie/tgiani/miniconda3/envs/nnpdf-dev/lib/python3.8/site-packages/reportengine/resourcebuilder.py", line 166, in execute_sequential
    result = self.get_result(callspec.function,
  File "/data/theorie/tgiani/miniconda3/envs/nnpdf-dev/lib/python3.8/site-packages/reportengine/resourcebuilder.py", line 175, in get_result
    fres =  function(**kwdict)
  File "/data/theorie/tgiani/nnpdfgit/nnpdf/n3fit/src/n3fit/performfit.py", line 251, in performfit
    result = pdf_gen_and_train_function(parameters)
  File "/data/theorie/tgiani/nnpdfgit/nnpdf/n3fit/src/n3fit/model_trainer.py", line 807, in hyperparametrizable
    self._generate_observables(
  File "/data/theorie/tgiani/nnpdfgit/nnpdf/n3fit/src/n3fit/model_trainer.py", line 490, in _generate_observables
    exp_layer = model_gen.observable_generator(exp_dict)
  File "/data/theorie/tgiani/nnpdfgit/nnpdf/n3fit/src/n3fit/model_gen.py", line 193, in observable_generator
    dataset.fktables(),
  File "/data/theorie/tgiani/nnpdfgit/nnpdf/validphys2/src/validphys/n3fit_data_utils.py", line 69, in fktables
    return [fk.get_np_fktable() for fk in self.fktables_data]
  File "/data/theorie/tgiani/nnpdfgit/nnpdf/validphys2/src/validphys/n3fit_data_utils.py", line 69, in <listcomp>
    return [fk.get_np_fktable() for fk in self.fktables_data]
  File "/data/theorie/tgiani/nnpdfgit/nnpdf/validphys2/src/validphys/coredata.py", line 159, in get_np_fktable
    ns = self.sigma.unstack(level=("data",), fill_value=0)
  File "/data/theorie/tgiani/miniconda3/envs/nnpdf-dev/lib/python3.8/site-packages/pandas/core/frame.py", line 7352, in unstack
    result = unstack(self, level, fill_value)
  File "/data/theorie/tgiani/miniconda3/envs/nnpdf-dev/lib/python3.8/site-packages/pandas/core/reshape/reshape.py", line 417, in unstack
    return _unstack_frame(obj, level, fill_value=fill_value)
  File "/data/theorie/tgiani/miniconda3/envs/nnpdf-dev/lib/python3.8/site-packages/pandas/core/reshape/reshape.py", line 444, in _unstack_frame
    return _Unstacker(
  File "/data/theorie/tgiani/miniconda3/envs/nnpdf-dev/lib/python3.8/site-packages/pandas/core/reshape/reshape.py", line 182, in get_result
    values, _ = self.get_new_values(values, fill_value)
  File "/data/theorie/tgiani/miniconda3/envs/nnpdf-dev/lib/python3.8/site-packages/pandas/core/reshape/reshape.py", line 209, in get_new_values
    sorted_values.reshape(length, width, stride)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 151. MiB for an array with shape (10000, 45, 44) and data type float64
```
for each replica I m asking `pvmem=15Gb`, and this was working fine with the old theories. This is the first time I m using th 400, doe it require more memory?

**Comment by tgiani** [comment] 2022-12-02 10:26
I have ```pineappl 0.5.8``` and ```numpy 1.20.2``` (which I should probably update)

**Comment by tgiani** [comment] 2022-12-02 10:26
but the 8gb you are requiring are `pvmem`?

**Comment by scarlehoff** [comment] 2022-12-02 11:12
What is pvmem? If it is virtual memory? (in the language of top) Because my 8 are resident.

**Comment by tgiani** [comment] 2022-12-02 11:30
yes it should be virtual memory per core

**Comment by Zaharid** [comment] 2022-12-02 13:08
Could we have a version of get_np_fktable that doesn’t copy the data?

**Comment by scarlehoff** [comment] 2022-12-02 13:21
> yes it should be virtual memory per core

Theory 400 also uses much more memory in disk. Maybe all of that is getting assigned to the fit process? Can you limit the actual memory in usage instead?

> Could we have a version of get_np_fktable that doesn’t copy the data?

The copy will happen sooner or later (because tf) and after tensorflow uses it the numpy copy should be dropped (not sure rn if at this point there are 3 copies in memory!)
I guess we can try to do pandas -> tf?

Another possibility is not keep the pandas rep around for the fit.

**Comment by goord** [comment] 2022-12-02 13:31
I also see that they are stored in double-precision arrays, is that necessary?

**Comment by tgiani** [comment] 2022-12-02 13:37
> Theory 400 also uses much more memory in disk. Maybe all of that is getting assigned to the fit process? Can you limit the actual memory in usage instead?

uhm not sure what you mean.  Do you mean to try to allocate a certain amount of physical memory as well?

**Comment by scarlehoff** [comment] 2022-12-02 13:39
Virtual memory, if I am not mistaken, is every kb assigned to the program, it doesn't matter is loaded or not.

@goord point is important. At that point in particular we don't need 64b, that was an oversight.

**Comment by Zaharid** [comment] 2022-12-02 13:44
haven’t thought about it much, but quoting from

https://www.tensorflow.org/tutorials/customization/basics#numpy_compatibility

> Tensors are explicitly converted to NumPy ndarrays using their .numpy() method. These conversions are typically cheap since the array and [tf.Tensor](https://www.tensorflow.org/api_docs/python/tf/Tensor) share the underlying memory representation,

**Comment by tgiani** [comment] 2022-12-02 13:52
@scarlehoff ok, but I m not sure I understand what you are suggesting to try

**Comment by scarlehoff** [comment] 2022-12-02 14:26
> @scarlehoff ok, but I m not sure I understand what you are suggesting to try

Just asking your cluster for resident memory or just to put a very big virtual memory requirement and hope it doesn't affect your chance in the queue

@Zaharid but the problem is that you start in pandas. Or do you mean keep it as tf in vp because getting numpy from there is cheap anyway?

**Comment by scarlehoff** [comment] 2022-12-02 14:50
> It should be logically possible to have pandas allocate the memory that gets used by tf

It is, but we need to go to custom operarors afaik

**Comment by goord** [comment] 2022-12-02 14:56
Another route may be to read and preprocess the FK table data in chunks, but this will also require a refactoring of the core data classes.

**Comment by Zaharid** [comment] 2022-12-02 15:00
What custom operators?

**Comment by tgiani** [comment] 2022-12-02 15:11
> Just asking your cluster for resident memory or just to put a very big virtual memory requirement and hope it doesn't affect your chance in the queue

I m already asking for the maximum pvmem I can. Talking with the cluster admin they are suggesting me to try to increase the number of cores as well to have more pvmem overall. If I use 8cores rather than 4 I have also to change `maxcores` in the runcard right?

**Comment by scarlehoff** [comment] 2022-12-02 15:21
Yes. Otherwise you won't take full advantage of it.

And sorry, I didn't fully realize this was 15 x 4. 60gb is crazy, there's something else wrong there!!!

**Comment by scarlehoff** [comment] 2022-12-02 15:22
(not necessarily in the cluster mind you, I need to have a look whether I see the same thing)

**Comment by tgiani** [comment] 2022-12-02 15:23
yes I also think there s something wrong

**Comment by tgiani** [comment] 2022-12-02 15:24
I asked to the cluster admin and they said 
```You say you ask for 15GB (per processor) which sounds like a lot; however, some programs have a tendency to ask for a lot of virtual memory and not actually use all of it. That is why there is usually a wide gap between the virtual size of a process and the amount reported as RSS or residential set size, which is the actual amount of RAM occupied.```
but I donno, still sounds quite a lo

**Comment by scarlehoff** [comment] 2022-12-02 15:24
> What custom operators?

The ones you can create with tf that Jesus was doing at some point. There you have more control of the memory within tf. But as said above, if these 60gb are reproducible then there's something else I should be worrying about.

**Comment by scarlehoff** [comment] 2022-12-02 17:17
@tgiani I'm getting 20 GB Virt with th 400 while only 10 GB with th 200. This difference makes perfect sense (/cc @felixhekhorn @andreab1997 we need to regenerate th 400 with 50 points in x sooner rather than later...) 

So maybe some of the programs installed in your cluster installation are adding extra memory? Or maybe you need to ask _also_ for resident memory (i.e., your memory problem is not the virtual memory but the actual memory being used, th 400 uses right now also a factor 2 with respect to th 200). Maybe you never happened to hit this limit

**Comment by tgiani** [comment] 2022-12-02 18:31
ok thank you, I m  trying to see if I can find a solution for stoomboot

**Comment by tgiani** [comment] 2022-12-02 21:43
looks like `pvmem` is not per core, but per process, which I m not sure what it means. If at the beginning of each job I look at how much vmem is actually set I see 16gb (and not 16x4). If I increase pvmem to 25gb it looks it s working (in principle 16gb is the maximum which can be set on stoomboot, but for the time being they are allowing me to run these jobs)

**Comment by scarlehoff** [comment] 2022-12-02 21:45
Ok, that's better. 60gb was really bad.

Then we should give some priority to reducing the size of the fktable now that it has become an actual problem.

**Comment by tgiani** [comment] 2022-12-02 21:47
yes, I think that 20gb is still quite a lot. If on stoomboot they limit jobs to 16gb I guess it means that in general that s already a lot, and other people might have the same issue on other machines

**Comment by tgiani** [comment] 2022-12-03 08:06
how long does it take for you to obtain a single replica using th 400? Longer than what you had with th 200?

**Comment by scarlehoff** [comment] 2022-12-03 08:36
Yes. Some go beyond 4 hours.

And, if you are memory-limited the fit might be swapping so it could take forever. If it doesn't work send me the runcard and I can run th 400 in Galileo (that way we don't have to bypass Stoomboot's limits)

@RoyStegeman @enocera I saw in the minutes something about fit variations with th400. Let's do first the slimming down of the theory please. Th 400 in its current state was just for benchmarking not for actual physics (as @tgiani is finding out the hard way)

@andreab1997 @felixhekhorn could you do this on Monday? It should be a question of rerunning the ekos with a grid of 50 points (plus applying said ekos). If you don't have time to do it let me know and I'll do it as soon as I am available next week. If you think it can be pushed down below 50 points all the better.

@andreab1997 what size of eko are you using for the theory variations? If it's 100 you should also slim those down before going to hadronic! (as an aside, please don't use the E906 grids I gave you some time ago because they are potentially broken :P)

**Comment by enocera** [comment] 2022-12-03 08:45
> @RoyStegeman @enocera I saw in the minutes something about fit variations with th400. Let's do first the slimming down of the theory please. Th 400 in its current state was just for benchmarking not for actual physics (as @tgiani is finding out the hard way)

For the time being only a wiki table has been asked for. Nobody is planning to run fits so far.

**Comment by tgiani** [comment] 2022-12-03 17:21
@scarlehoff for the time being I was able to run the fit, should be ready soon

**Comment by tgiani** [comment] 2022-12-09 06:55
@scarlehoff when running a report for a fit done with th400, are you able to do this on your laptop? I ve tried on mine but it fails, I guess also here a lot of memory is required? I m trying to produce it by running a separate job now

**Comment by scarlehoff** [comment] 2022-12-09 07:26
This might be composed with issue #1637 (have you already pulled the fix for that?)

I'm able to run reports in a desktop with 16gb of ram, I never use my laptop for that.

**Comment by scarlehoff** [comment] 2022-12-12 11:58
I'm going to close this. Theory 400 will be recomputed with a lower memory footprint.

In addition some bugs might have been found... (hopefully not...)

**Closed by scarlehoff** 2022-12-12 11:58 UTC
