### ISSUE TITLE
Problem with vp-comparefits

### ISSUE THREAD

**Issue by enocera** [NNPDF/nnpdf#1657] opened 2023-01-06 09:21 UTC
For some fits, when I try to do `vp-comparefits` I get the attached error message.
[error.txt](https://github.com/NNPDF/nnpdf/files/10358997/error.txt)

**Comment by Zaharid** [comment] 2023-01-06 11:23
This seems to be happening with the arclength plots

```
  File "/data/theorie/enocera/nnpdfgit/nnpdf/validphys2/src/validphys/arclength.py", line 102, in plot_arc_lengths
    ax.errorbar(
  File "/data/theorie/enocera/miniconda3/envs/nnpdf-dev/lib/python3.8/site-packages/matplotlib/__init__.py", line 1423, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/data/theorie/enocera/miniconda3/envs/nnpdf-dev/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 3595, in errorbar
    raise ValueError(
ValueError: 'yerr' must not contain negative values
```

**Comment by Zaharid** [comment] 2023-01-17 12:21
This error hs surfaced because of an updated in matplotlib, as described in #1664. It is howerver not readily obvious to me why this is happening in the arclength plots.

**Comment by scarlehoff** [comment] 2023-01-18 03:58
Is this fixed by #1664?

**Comment by Zaharid** [comment] 2023-01-18 10:38
No, as per the comment above.

**Comment by scarlehoff** [comment] 2023-01-18 10:40
Is the problem now that the arclengths are producing negative errorbars?

(i.e., if @enocera runs the comparefits again, it will work _but_ the arclenghts will have 0-error bars?)

**Comment by Zaharid** [comment] 2023-01-18 17:34
No. The problem is that an upgrade of matplotlib now checks if `yerr` is negative, while it didn't before.

It would give zero errors for Emanuele instead of crashing if he were to downgrade the matplotlib version.

But there is a logic error that needs to be fixed somewhere.

**Comment by comane** [comment] 2023-02-27 21:35
@enocera, @Zaharid, my guess is that the problem arises from these lines of the code within `validphys.arclength.plot_arc_lengths`:
`yvalues = arclengths.stats.central_value()`
`ylower, yupper = arclengths.stats.errorbar68()`
`ylower = yvalues - ylower`
`yupper = yupper - yvalues`
Some of the replicas might be shorter than the central replica. The problem is thus probably fixed by taking the absolute value of the difference.

Another possible issue might be in `validphys.arclength.arc_lengths`, namely, in
`res += integrate.simps(1 + np.square(fdiff), ixgrid[1][1:])`
It looks like a square root is missing here:
`res += integrate.simps(np.sqrt(1 + np.square(fdiff)), ixgrid[1][1:])`

#1681

**Comment by comane** [comment] 2023-02-27 21:35
#1681

**Closed** 2023-03-09 09:53 UTC
