### ISSUE TITLE
Use pineappl for convolution in vp

### ISSUE THREAD

**Issue by Radonirinaunimi** [NNPDF/nnpdf#2105] opened 2024-06-06 09:48 UTC
Using pineappl to perform the convolution in vp unlock various features (beyond unpolarized pp).

**Comment by scarlehoff** [comment] 2024-06-06 09:51
This is a duplicate of https://github.com/NNPDF/nnpdf/issues/1961

**Closed by scarlehoff** 2024-06-06 09:51 UTC
Labels: enhancement
