### ISSUE TITLE
Error propagation in normalised data-theory comparisons

### ISSUE THREAD

**Issue by J-M-Moore** [NNPDF/nnpdf#1663] opened 2023-01-17 12:15 UTC
There needs to be an absolute value in this line of dataplots.py to ensure that errors do not become negative in normalised data-theory comparisons: https://github.com/NNPDF/nnpdf/blob/dce797346f664ca19e7a676a0d840c57938c1e9e/validphys2/src/validphys/dataplots.py#L269

**Comment by Zaharid** [comment] 2023-01-17 12:19
Uh. Duplicate of #1664. Thought you were making a PR!

**Closed by Zaharid** 2023-01-17 12:19 UTC
